### ISSUE TITLE
 CUDA out of memory after few messages in the chat?

### ISSUE THREAD

**Issue by Yuugirihime** [TavernAI/TavernAI-v1#15]
After some time it just stops generating answers and does this:

    msg: 'KoboldAI ran out of memory: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 14.76 GiB total capacity; 13.65 GiB already allocated; 9.88 MiB free; 13.85 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF',
    type: 'out_of_memory.gpu.cuda'

However i can switch to another character and there stuff would be OK (until the error appears again). 
Any suggestions what to do?
![Снимок экрана 2023-01-25 072245](https://user-images.githubusercontent.com/114836114/214479402-15c66772-ebe9-4a7d-b58e-2a0046eb6aef.png)

**Comment by TavernAI** [comment]
You don't have enough video memory for the size of the text you are sending. You need to reduce the context size. Because when the chat size increases, it requires more resources. It should also be borne in mind that you should have some free video memory before generating, so you should play with the settings for running the model in KobaldAI, and for example run some of the layers of the model in RAM. In general, this is a problem unrelated to the TavernAI.

**Comment by Yuugirihime** [comment]
I see, thank you for your answer! I thought colab wouldn't have such problems, haha, but seems even the holy tpu isn't the savior.

**Comment by Deus-Desu** [comment]
For me the out of memory error consistently appears after just 12-16 short messages. At this point Collab exceeds all 15Gb of T4 VRAM. Is this really a normal behavior?

**Comment by Deus-Desu** [comment]
The issue seems to be resolved by switching preset to "GPU-Pygmalion-6b" instead of the default "Classic-Pygmalion-6b"

**Comment by Borov666** [comment]
The problem has been fixed, by default, the context size for the GPU was set to 1400 in Colab notebook.
